name: cdds-dev
channels:
  - conda-forge
  - nodefaults 
dependencies:
  - cf-units=3.2.0
  - cftime=1.6.2
  - cmor=3.13.0
  - compliance-checker=5.4.2
  - dask-core=2023.5
  - debugpy=1.6.6
  - gsw=3.6.19
  - iris=3.7.1
  - libmo_unpack=3.1.2
  - metomi-isodatetime=1!3.0.0
  - mike=2.0.0
  - mkdocs=1.5.3
  - mkdocs-autorefs=1.0.1
  - mkdocs-gen-files=0.4.0
  - mkdocs-literate-nav=0.4.1
  - mkdocs-material=8.5.11
  - mkdocs-material-extensions=1.3.1
  - mkdocstrings=0.24.1
  - mkdocstrings-python=1.9.0
  - mo_pack=0.2.0
  - nccmp=1.10.0.0
  - nco=5.3.4
  - numpy=1.26.4
  - mypy
  - mypy_extensions
  - myst-parser=0.18.1
  - netcdf4=1.7.2
  - pandas=2.0.3
  - pep8=1.7.1
  - pika=1.2.0
  - pip=25.1.1
  - pre-commit=2.20.0
  - pyproj=3.5.0
  - pytest=7.1.2
  - pytest-cov=3.0.0
  - python=3.10
  - regex=2024.11.6
  - ruff=0.14.8
  - scipy=1.15.2
  - sphinx=4.2.0
  - pip:
    - dreqpy==1.0.29
    - mkdocs-section-index==0.3.8
#    - git+ssh://git@github.com-deploy/MetOffice/CDDS.git@v<location>#egg=cdds
#    - git+ssh://git@github.com-deploy/MetOffice/CDDS.git@v<location>#egg=mip_convert&subdirectory=mip_convert
variables:
    CYLC_VERSION: 8
    LC_ALL: en_GB.UTF-8
    TZ: UTC
# prefix: $CDDS_HOME/conda_environments/cdds-dev
